development: &common_settings
  cluster_name: "Faster"
  dashboard_url: "/pun/dev/HPC_Mosiac"
  file_app_url: "/pun/sys/files/fs"
  file_editor_url: "/pun/sys/file-editor/edit"
  home_page: "https://hprc.tamu.edu"
  request_email: "help@hprc.tamu.edu"
  help_email: "help@hprc.tamu.edu"
  modules_db_path: "/sw/hprc/sw/portal_utils/modules.sqlite3"
  driver_scripts_path: "/var/www/ood/apps/dev/s_mittal04/HPC_Mosiac/machine_driver_scripts"
  hprcbot_route: 'http://courant.hprc.tamu.edu:8553'
  default_python_venv: "/sw/hprc/sw/Python/virtualenvs/Python/3.8.6/default_dashboard_python-env/"

production:
  <<: *common_settings
  dashboard_url: "/pun/dev/HPC_Mosiac"
  request_email: "help@hprc.tamu.edu"
  driver_scripts_path: "/var/www/ood/apps/dev/HPC_Mosiac/machine_driver_scripts"
  help_email: "help@hprc.tamu.edu"
